### ISSUE TITLE
Add me

### ISSUE THREAD

**Issue by ashumeow** [Chennaipy/libcipher#14]
Can you add me in the team?
I would like to freely add some more simple python repositories to ChennaiPy.
I'm good in Python 2.7 legacy version (hacking & security) and also, okay-ish in Python 3.4 (basics and some with django)

**Comment by shrayasr** [comment]
Hi Aswini, 

Thanks for the initiative. If you'd like to take up such a project then we request you to write in to the mailing list with ideas and look at the response of the community. Based on that @bravegnu can make a repo on the organization and give you commit access to it. 

Hope that clears it up?

**Comment by bravegnu** [comment]
+1 for @shrayasr comment. You can join the mailing list at https://mail.python.org/mailman/listinfo/chennaipy

**Comment by ashumeow** [comment]
Thanks for letting me know. Yup, i joined the mailing list (^_^)

**Comment by shrayasr** [comment]
No problem :)
