### ISSUE TITLE
Add Caesar Cipher encryption and decryption

### ISSUE THREAD

**Issue by bravegnu** [Chennaipy/libcipher#4]
Create a module `caesar`, with functions `encrypt()` and `decrypt()` that implements the Caesar cipher. Reference implementation: https://inventwithpython.com/hacking/chapter6.html
- [ ] pep8
- [ ] unit tests
- [ ] docstring
- [ ] API manual
- [ ] changelog

**Comment by rajeshkumargp** [comment]
Hi I like to code this Caesar cipher encryption and decryption.

**Comment by shrayasr** [comment]
Hi Rajesh, 

Krishna has already started with an implementation in #10. Why don't you pick up one of the other tasks? :)

**Comment by rajeshkumargp** [comment]
Ya sure,
I will check.

by
Rajeshkumar.P

**Comment by bravegnu** [comment]
Fixed by #10
