### ISSUE TITLE
Add Transposition Cipher Encryption

### ISSUE THREAD

**Issue by bravegnu** [Chennaipy/libcipher#5]
Create a module `transpos`, with functions `encrypt()` that implements the Transposition Cipher. Reference implementation: https://inventwithpython.com/hacking/chapter8.html
- [ ] pep8
- [ ] unit tests
- [ ] docstring
- [ ] API manual
- [ ] changelog

**Comment by rajeshkumargp** [comment]
I like to work on this task.

**Comment by shrayasr** [comment]
Go for it :+1:

**Comment by rajeshkumargp** [comment]
I have committed code in https://github.com/rajeshkumargp/libcipher.
Kindly review it.

**Comment by bravegnu** [comment]
Closed by #13
