### ISSUE TITLE
Add Transposition Cipher Decryption

### ISSUE THREAD

**Issue by bravegnu** [Chennaipy/libcipher#6]
Add  the function `decrypt()` to the module `transpos` that implements the Transposition Cipher Decryption. Reference implementation: https://inventwithpython.com/hacking/chapter9.html
- [ ] pep8
- [ ] unit tests
- [ ] docstring
- [ ] changelog

**Comment by gnurenga** [comment]
I like to take up this activity

**Comment by shrayasr** [comment]
:+1:

**Comment by bravegnu** [comment]
Closed by #12
