### ISSUE TITLE
Add utility function to detect English

### ISSUE THREAD

**Issue by bravegnu** [Chennaipy/libcipher#7]
Add a module `utils` with class `EnglishChecker`, that loads the specified dictionary file on init. and provides a method  `is_english()` to detect whether a given text is English text. Reference implementation: https://inventwithpython.com/hacking/chapter12.html
- [ ] pep8
- [ ] unit tests
- [ ] docstring
- [ ] API manual
- [ ] changelog

**Comment by Anupama-Github** [comment]
@bravegnu  I am working on this but do not know how to update API manual and changelog. I have added utiils.rst in doc folder in a format similar to the existing reverse.rst
I also added the line "\* :feature: '2' Added utils module" to the changelog.rst file. Could you guide me on doing these steps correctly?

Thank you

**Comment by bravegnu** [comment]
Looks like you are on the right track. You need to add `utils` to the `toctree` in `index.rst`

**Comment by Anupama-Github** [comment]
@bravegnu Thank you I have done so
However my pull request has returned the status Travis CI build failed I will recheck my code, any pointers from you would be helpful

**Comment by bravegnu** [comment]
Closed by #11
